_BASE_: "../Base-RCNN-DilatedC5.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
INPUT:
  # MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 4000
DATASETS:
  TRAIN: ('voc_2007_train_wsl', 'voc_2007_val_wsl')
  TEST: ('voc_2007_test',)
  # TEST: ('voc_2007_test', 'voc_2007_train', 'voc_2007_val')
SOLVER:
  STEPS: (8000, 10500)
  MAX_ITER: 12000  # 17.4 epochs
  WARMUP_ITERS: 0
  IMS_PER_BATCH: 4
  BASE_LR: 0.002
TEST:
  EVAL_PERIOD: 2000
OUTPUT_DIR: "output/fsod/voc_faster_rcnn_DC5_baseline_wsl/"
