_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  META_ARCHITECTURE: "RetinaNet"
  WEIGHTS: "models/VGG/VGG_ILSVRC_16_layers_v1_d2.pkl"
  BACKBONE:
    NAME: "build_vgg_backbone"
    FREEZE_AT: 2
  VGG:
    DEPTH: 16
    CONV5_DILATION: 2
  ANCHOR_GENERATOR:
    SIZES: [[64, 128, 256, 512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  RETINANET:
    IN_FEATURES: ["plain5"]
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.0
#    REG_BRANCH: FALSE
    NMS_THRESH_TEST: 0.3
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024, 1056, 1088, 1120, 1152, 1184, 1216)
  #MIN_SIZE_TRAIN: (480, 576, 688, 864, 1200)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 688
  MAX_SIZE_TEST: 2000
  CROP:
    ENABLED: True
SOLVER:
  STEPS: (15000, 20000)
  MAX_ITER: 25000  # 28.0 epochs for 07
  WARMUP_ITERS: 500
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  #WEIGHT_DECAY: 0.0005
  #BIAS_LR_FACTOR: 2.0
  #WEIGHT_DECAY_BIAS: 0.0
TEST:
  AUG:
    ENABLED: True
    MIN_SIZES: (480, 576, 672, 768, 864, 960, 1056, 1152)
    #MIN_SIZES: (480, 576, 688, 864, 1200)
    MAX_SIZE: 4000
    FLIP: True
  EVAL_PERIOD: 10000
WSL:
  #ITER_SIZE: 32
  #MEAN_LOSS: False
  ITER_SIZE: 1
  MEAN_LOSS: True
DATASETS:
  TRAIN: ('voc_2007_trainval',)
  TEST: ('voc_2007_test',)
  PROPOSAL_FILES_TRAIN: ()
  PROPOSAL_FILES_TEST: ()
